//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisComWeb.Business.ServicioConsultaDNIRUC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RUC_Response", Namespace="integradores.jelaf.pe")]
    [System.SerializableAttribute()]
    public partial class RUC_Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_CONTRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAZON_SOCIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOM_FISCALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADO_CONTRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONDI_CONTRField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TIPO_CONTR {
            get {
                return this.TIPO_CONTRField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_CONTRField, value) != true)) {
                    this.TIPO_CONTRField = value;
                    this.RaisePropertyChanged("TIPO_CONTR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RAZON_SOCIAL {
            get {
                return this.RAZON_SOCIALField;
            }
            set {
                if ((object.ReferenceEquals(this.RAZON_SOCIALField, value) != true)) {
                    this.RAZON_SOCIALField = value;
                    this.RaisePropertyChanged("RAZON_SOCIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DOM_FISCAL {
            get {
                return this.DOM_FISCALField;
            }
            set {
                if ((object.ReferenceEquals(this.DOM_FISCALField, value) != true)) {
                    this.DOM_FISCALField = value;
                    this.RaisePropertyChanged("DOM_FISCAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ESTADO_CONTR {
            get {
                return this.ESTADO_CONTRField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADO_CONTRField, value) != true)) {
                    this.ESTADO_CONTRField = value;
                    this.RaisePropertyChanged("ESTADO_CONTR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CONDI_CONTR {
            get {
                return this.CONDI_CONTRField;
            }
            set {
                if ((object.ReferenceEquals(this.CONDI_CONTRField, value) != true)) {
                    this.CONDI_CONTRField = value;
                    this.RaisePropertyChanged("CONDI_CONTR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DNI_Response", Namespace="integradores.jelaf.pe")]
    [System.SerializableAttribute()]
    public partial class DNI_Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AP_PATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AP_MATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AP_PATERNO {
            get {
                return this.AP_PATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.AP_PATERNOField, value) != true)) {
                    this.AP_PATERNOField = value;
                    this.RaisePropertyChanged("AP_PATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AP_MATERNO {
            get {
                return this.AP_MATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.AP_MATERNOField, value) != true)) {
                    this.AP_MATERNOField = value;
                    this.RaisePropertyChanged("AP_MATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NOMBRES {
            get {
                return this.NOMBRESField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRESField, value) != true)) {
                    this.NOMBRESField = value;
                    this.RaisePropertyChanged("NOMBRES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="integradores.jelaf.pe", ConfigurationName="ServicioConsultaDNIRUC.WsConsultaSoap")]
    public interface WsConsultaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RUC del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/CONSULTAR_RUC", ReplyAction="*")]
        SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse CONSULTAR_RUC(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/CONSULTAR_RUC", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse> CONSULTAR_RUCAsync(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DNI del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/CONSULTAR_DNI", ReplyAction="*")]
        SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse CONSULTAR_DNI(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/CONSULTAR_DNI", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse> CONSULTAR_DNIAsync(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CONSULTAR_RUCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CONSULTAR_RUC", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequestBody Body;
        
        public CONSULTAR_RUCRequest() {
        }
        
        public CONSULTAR_RUCRequest(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class CONSULTAR_RUCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RUC;
        
        public CONSULTAR_RUCRequestBody() {
        }
        
        public CONSULTAR_RUCRequestBody(string RUC) {
            this.RUC = RUC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CONSULTAR_RUCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CONSULTAR_RUCResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCResponseBody Body;
        
        public CONSULTAR_RUCResponse() {
        }
        
        public CONSULTAR_RUCResponse(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class CONSULTAR_RUCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServicioConsultaDNIRUC.RUC_Response CONSULTAR_RUCResult;
        
        public CONSULTAR_RUCResponseBody() {
        }
        
        public CONSULTAR_RUCResponseBody(SisComWeb.Business.ServicioConsultaDNIRUC.RUC_Response CONSULTAR_RUCResult) {
            this.CONSULTAR_RUCResult = CONSULTAR_RUCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CONSULTAR_DNIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CONSULTAR_DNI", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequestBody Body;
        
        public CONSULTAR_DNIRequest() {
        }
        
        public CONSULTAR_DNIRequest(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class CONSULTAR_DNIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DNI;
        
        public CONSULTAR_DNIRequestBody() {
        }
        
        public CONSULTAR_DNIRequestBody(string DNI) {
            this.DNI = DNI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CONSULTAR_DNIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CONSULTAR_DNIResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIResponseBody Body;
        
        public CONSULTAR_DNIResponse() {
        }
        
        public CONSULTAR_DNIResponse(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class CONSULTAR_DNIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServicioConsultaDNIRUC.DNI_Response CONSULTAR_DNIResult;
        
        public CONSULTAR_DNIResponseBody() {
        }
        
        public CONSULTAR_DNIResponseBody(SisComWeb.Business.ServicioConsultaDNIRUC.DNI_Response CONSULTAR_DNIResult) {
            this.CONSULTAR_DNIResult = CONSULTAR_DNIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsConsultaSoapChannel : SisComWeb.Business.ServicioConsultaDNIRUC.WsConsultaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsConsultaSoapClient : System.ServiceModel.ClientBase<SisComWeb.Business.ServicioConsultaDNIRUC.WsConsultaSoap>, SisComWeb.Business.ServicioConsultaDNIRUC.WsConsultaSoap {
        
        public WsConsultaSoapClient() {
        }
        
        public WsConsultaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsConsultaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsConsultaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsConsultaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse SisComWeb.Business.ServicioConsultaDNIRUC.WsConsultaSoap.CONSULTAR_RUC(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest request) {
            return base.Channel.CONSULTAR_RUC(request);
        }
        
        public SisComWeb.Business.ServicioConsultaDNIRUC.RUC_Response CONSULTAR_RUC(string RUC) {
            SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest inValue = new SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest();
            inValue.Body = new SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequestBody();
            inValue.Body.RUC = RUC;
            SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse retVal = ((SisComWeb.Business.ServicioConsultaDNIRUC.WsConsultaSoap)(this)).CONSULTAR_RUC(inValue);
            return retVal.Body.CONSULTAR_RUCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse> SisComWeb.Business.ServicioConsultaDNIRUC.WsConsultaSoap.CONSULTAR_RUCAsync(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest request) {
            return base.Channel.CONSULTAR_RUCAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse> CONSULTAR_RUCAsync(string RUC) {
            SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest inValue = new SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest();
            inValue.Body = new SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_RUCRequestBody();
            inValue.Body.RUC = RUC;
            return ((SisComWeb.Business.ServicioConsultaDNIRUC.WsConsultaSoap)(this)).CONSULTAR_RUCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse SisComWeb.Business.ServicioConsultaDNIRUC.WsConsultaSoap.CONSULTAR_DNI(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest request) {
            return base.Channel.CONSULTAR_DNI(request);
        }
        
        public SisComWeb.Business.ServicioConsultaDNIRUC.DNI_Response CONSULTAR_DNI(string DNI) {
            SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest inValue = new SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest();
            inValue.Body = new SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequestBody();
            inValue.Body.DNI = DNI;
            SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse retVal = ((SisComWeb.Business.ServicioConsultaDNIRUC.WsConsultaSoap)(this)).CONSULTAR_DNI(inValue);
            return retVal.Body.CONSULTAR_DNIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse> SisComWeb.Business.ServicioConsultaDNIRUC.WsConsultaSoap.CONSULTAR_DNIAsync(SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest request) {
            return base.Channel.CONSULTAR_DNIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse> CONSULTAR_DNIAsync(string DNI) {
            SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest inValue = new SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest();
            inValue.Body = new SisComWeb.Business.ServicioConsultaDNIRUC.CONSULTAR_DNIRequestBody();
            inValue.Body.DNI = DNI;
            return ((SisComWeb.Business.ServicioConsultaDNIRUC.WsConsultaSoap)(this)).CONSULTAR_DNIAsync(inValue);
        }
    }
}
