//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisComWeb.Services.ServiceFE {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="integradores.jelaf.pe", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="integradores.jelaf.pe", ConfigurationName="ServiceFE.Ws_SeeFacteSoap")]
    public interface Ws_SeeFacteSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetValueInvoice", ReplyAction="*")]
        SisComWeb.Services.ServiceFE.SetValueInvoiceResponse SetValueInvoice(SisComWeb.Services.ServiceFE.SetValueInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetValueInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetValueInvoiceResponse> SetValueInvoiceAsync(SisComWeb.Services.ServiceFE.SetValueInvoiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetInvoice", ReplyAction="*")]
        SisComWeb.Services.ServiceFE.SetInvoiceResponse SetInvoice(SisComWeb.Services.ServiceFE.SetInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetInvoiceResponse> SetInvoiceAsync(SisComWeb.Services.ServiceFE.SetInvoiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/GetValidarDocument", ReplyAction="*")]
        SisComWeb.Services.ServiceFE.GetValidarDocumentResponse GetValidarDocument(SisComWeb.Services.ServiceFE.GetValidarDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/GetValidarDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.GetValidarDocumentResponse> GetValidarDocumentAsync(SisComWeb.Services.ServiceFE.GetValidarDocumentRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetDocumentNote", ReplyAction="*")]
        SisComWeb.Services.ServiceFE.SetDocumentNoteResponse SetDocumentNote(SisComWeb.Services.ServiceFE.SetDocumentNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetDocumentNote", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetDocumentNoteResponse> SetDocumentNoteAsync(SisComWeb.Services.ServiceFE.SetDocumentNoteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetVoidedDocument", ReplyAction="*")]
        SisComWeb.Services.ServiceFE.SetVoidedDocumentResponse SetVoidedDocument(SisComWeb.Services.ServiceFE.SetVoidedDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetVoidedDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetVoidedDocumentResponse> SetVoidedDocumentAsync(SisComWeb.Services.ServiceFE.SetVoidedDocumentRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetComprobanteRet", ReplyAction="*")]
        SisComWeb.Services.ServiceFE.SetComprobanteRetResponse SetComprobanteRet(SisComWeb.Services.ServiceFE.SetComprobanteRetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetComprobanteRet", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetComprobanteRetResponse> SetComprobanteRetAsync(SisComWeb.Services.ServiceFE.SetComprobanteRetRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/GetParametro", ReplyAction="*")]
        SisComWeb.Services.ServiceFE.GetParametroResponse GetParametro(SisComWeb.Services.ServiceFE.GetParametroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/GetParametro", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.GetParametroResponse> GetParametroAsync(SisComWeb.Services.ServiceFE.GetParametroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetValueInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetValueInvoice", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.SetValueInvoiceRequestBody Body;
        
        public SetValueInvoiceRequest() {
        }
        
        public SetValueInvoiceRequest(SisComWeb.Services.ServiceFE.SetValueInvoiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetValueInvoiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Persona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SisComWeb.Services.ServiceFE.ArrayOfString DetInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SisComWeb.Services.ServiceFE.ArrayOfString DocInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SisComWeb.Services.ServiceFE.ArrayOfString Aditional;
        
        public SetValueInvoiceRequestBody() {
        }
        
        public SetValueInvoiceRequestBody(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Services.ServiceFE.ArrayOfString Aditional) {
            this.Security = Security;
            this.Persona = Persona;
            this.CInvoice = CInvoice;
            this.DetInvoice = DetInvoice;
            this.DocInvoice = DocInvoice;
            this.Aditional = Aditional;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetValueInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetValueInvoiceResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.SetValueInvoiceResponseBody Body;
        
        public SetValueInvoiceResponse() {
        }
        
        public SetValueInvoiceResponse(SisComWeb.Services.ServiceFE.SetValueInvoiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetValueInvoiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseW SetValueInvoiceResult;
        
        public SetValueInvoiceResponseBody() {
        }
        
        public SetValueInvoiceResponseBody(SisComWeb.Business.ServiceFE.ResponseW SetValueInvoiceResult) {
            this.SetValueInvoiceResult = SetValueInvoiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetInvoice", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.SetInvoiceRequestBody Body;
        
        public SetInvoiceRequest() {
        }
        
        public SetInvoiceRequest(SisComWeb.Services.ServiceFE.SetInvoiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetInvoiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Persona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SisComWeb.Services.ServiceFE.ArrayOfString DetInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SisComWeb.Services.ServiceFE.ArrayOfString DocInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SisComWeb.Services.ServiceFE.ArrayOfString Aditional;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool EnvioAsync;
        
        public SetInvoiceRequestBody() {
        }
        
        public SetInvoiceRequestBody(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Services.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            this.Security = Security;
            this.Persona = Persona;
            this.CInvoice = CInvoice;
            this.DetInvoice = DetInvoice;
            this.DocInvoice = DocInvoice;
            this.Aditional = Aditional;
            this.EnvioAsync = EnvioAsync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetInvoiceResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.SetInvoiceResponseBody Body;
        
        public SetInvoiceResponse() {
        }
        
        public SetInvoiceResponse(SisComWeb.Services.ServiceFE.SetInvoiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetInvoiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseW SetInvoiceResult;
        
        public SetInvoiceResponseBody() {
        }
        
        public SetInvoiceResponseBody(SisComWeb.Business.ServiceFE.ResponseW SetInvoiceResult) {
            this.SetInvoiceResult = SetInvoiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValidarDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValidarDocument", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.GetValidarDocumentRequestBody Body;
        
        public GetValidarDocumentRequest() {
        }
        
        public GetValidarDocumentRequest(SisComWeb.Services.ServiceFE.GetValidarDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class GetValidarDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TipoDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Serie;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NroDocument;
        
        public GetValidarDocumentRequestBody() {
        }
        
        public GetValidarDocumentRequestBody(SisComWeb.Business.ServiceFE.Security Security, string TipoDoc, string Serie, string NroDocument) {
            this.Security = Security;
            this.TipoDoc = TipoDoc;
            this.Serie = Serie;
            this.NroDocument = NroDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValidarDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValidarDocumentResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.GetValidarDocumentResponseBody Body;
        
        public GetValidarDocumentResponse() {
        }
        
        public GetValidarDocumentResponse(SisComWeb.Services.ServiceFE.GetValidarDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class GetValidarDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseDocument GetValidarDocumentResult;
        
        public GetValidarDocumentResponseBody() {
        }
        
        public GetValidarDocumentResponseBody(SisComWeb.Business.ServiceFE.ResponseDocument GetValidarDocumentResult) {
            this.GetValidarDocumentResult = GetValidarDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDocumentNoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDocumentNote", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.SetDocumentNoteRequestBody Body;
        
        public SetDocumentNoteRequest() {
        }
        
        public SetDocumentNoteRequest(SisComWeb.Services.ServiceFE.SetDocumentNoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetDocumentNoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Persona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DocumentNote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SisComWeb.Services.ServiceFE.ArrayOfString DetDocumentNote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SisComWeb.Services.ServiceFE.ArrayOfString DocDocumentNote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SisComWeb.Services.ServiceFE.ArrayOfString Aditional;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool EnvioAsync;
        
        public SetDocumentNoteRequestBody() {
        }
        
        public SetDocumentNoteRequestBody(SisComWeb.Business.ServiceFE.Security Security, string Persona, string DocumentNote, SisComWeb.Services.ServiceFE.ArrayOfString DetDocumentNote, SisComWeb.Services.ServiceFE.ArrayOfString DocDocumentNote, SisComWeb.Services.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            this.Security = Security;
            this.Persona = Persona;
            this.DocumentNote = DocumentNote;
            this.DetDocumentNote = DetDocumentNote;
            this.DocDocumentNote = DocDocumentNote;
            this.Aditional = Aditional;
            this.EnvioAsync = EnvioAsync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDocumentNoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDocumentNoteResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.SetDocumentNoteResponseBody Body;
        
        public SetDocumentNoteResponse() {
        }
        
        public SetDocumentNoteResponse(SisComWeb.Services.ServiceFE.SetDocumentNoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetDocumentNoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseW SetDocumentNoteResult;
        
        public SetDocumentNoteResponseBody() {
        }
        
        public SetDocumentNoteResponseBody(SisComWeb.Business.ServiceFE.ResponseW SetDocumentNoteResult) {
            this.SetDocumentNoteResult = SetDocumentNoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetVoidedDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetVoidedDocument", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.SetVoidedDocumentRequestBody Body;
        
        public SetVoidedDocumentRequest() {
        }
        
        public SetVoidedDocumentRequest(SisComWeb.Services.ServiceFE.SetVoidedDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetVoidedDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string VoidedDocument;
        
        public SetVoidedDocumentRequestBody() {
        }
        
        public SetVoidedDocumentRequestBody(SisComWeb.Business.ServiceFE.Security Security, string VoidedDocument) {
            this.Security = Security;
            this.VoidedDocument = VoidedDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetVoidedDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetVoidedDocumentResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.SetVoidedDocumentResponseBody Body;
        
        public SetVoidedDocumentResponse() {
        }
        
        public SetVoidedDocumentResponse(SisComWeb.Services.ServiceFE.SetVoidedDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetVoidedDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseW SetVoidedDocumentResult;
        
        public SetVoidedDocumentResponseBody() {
        }
        
        public SetVoidedDocumentResponseBody(SisComWeb.Business.ServiceFE.ResponseW SetVoidedDocumentResult) {
            this.SetVoidedDocumentResult = SetVoidedDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetComprobanteRetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetComprobanteRet", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.SetComprobanteRetRequestBody Body;
        
        public SetComprobanteRetRequest() {
        }
        
        public SetComprobanteRetRequest(SisComWeb.Services.ServiceFE.SetComprobanteRetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetComprobanteRetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Persona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ComprobanteC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SisComWeb.Services.ServiceFE.ArrayOfString ComprobanteD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SisComWeb.Services.ServiceFE.ArrayOfString Aditional;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool EnvioAsync;
        
        public SetComprobanteRetRequestBody() {
        }
        
        public SetComprobanteRetRequestBody(SisComWeb.Business.ServiceFE.Security Security, string Persona, string ComprobanteC, SisComWeb.Services.ServiceFE.ArrayOfString ComprobanteD, SisComWeb.Services.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            this.Security = Security;
            this.Persona = Persona;
            this.ComprobanteC = ComprobanteC;
            this.ComprobanteD = ComprobanteD;
            this.Aditional = Aditional;
            this.EnvioAsync = EnvioAsync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetComprobanteRetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetComprobanteRetResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.SetComprobanteRetResponseBody Body;
        
        public SetComprobanteRetResponse() {
        }
        
        public SetComprobanteRetResponse(SisComWeb.Services.ServiceFE.SetComprobanteRetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetComprobanteRetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseW SetComprobanteRetResult;
        
        public SetComprobanteRetResponseBody() {
        }
        
        public SetComprobanteRetResponseBody(SisComWeb.Business.ServiceFE.ResponseW SetComprobanteRetResult) {
            this.SetComprobanteRetResult = SetComprobanteRetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParametroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParametro", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.GetParametroRequestBody Body;
        
        public GetParametroRequest() {
        }
        
        public GetParametroRequest(SisComWeb.Services.ServiceFE.GetParametroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class GetParametroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        public GetParametroRequestBody() {
        }
        
        public GetParametroRequestBody(SisComWeb.Business.ServiceFE.Security Security) {
            this.Security = Security;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParametroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParametroResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServiceFE.GetParametroResponseBody Body;
        
        public GetParametroResponse() {
        }
        
        public GetParametroResponse(SisComWeb.Services.ServiceFE.GetParametroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class GetParametroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.RParametro GetParametroResult;
        
        public GetParametroResponseBody() {
        }
        
        public GetParametroResponseBody(SisComWeb.Business.ServiceFE.RParametro GetParametroResult) {
            this.GetParametroResult = GetParametroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Ws_SeeFacteSoapChannel : SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ws_SeeFacteSoapClient : System.ServiceModel.ClientBase<SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap>, SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap {
        
        public Ws_SeeFacteSoapClient() {
        }
        
        public Ws_SeeFacteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ws_SeeFacteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_SeeFacteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_SeeFacteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Services.ServiceFE.SetValueInvoiceResponse SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.SetValueInvoice(SisComWeb.Services.ServiceFE.SetValueInvoiceRequest request) {
            return base.Channel.SetValueInvoice(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseW SetValueInvoice(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Services.ServiceFE.ArrayOfString Aditional) {
            SisComWeb.Services.ServiceFE.SetValueInvoiceRequest inValue = new SisComWeb.Services.ServiceFE.SetValueInvoiceRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.SetValueInvoiceRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.CInvoice = CInvoice;
            inValue.Body.DetInvoice = DetInvoice;
            inValue.Body.DocInvoice = DocInvoice;
            inValue.Body.Aditional = Aditional;
            SisComWeb.Services.ServiceFE.SetValueInvoiceResponse retVal = ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).SetValueInvoice(inValue);
            return retVal.Body.SetValueInvoiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetValueInvoiceResponse> SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.SetValueInvoiceAsync(SisComWeb.Services.ServiceFE.SetValueInvoiceRequest request) {
            return base.Channel.SetValueInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetValueInvoiceResponse> SetValueInvoiceAsync(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Services.ServiceFE.ArrayOfString Aditional) {
            SisComWeb.Services.ServiceFE.SetValueInvoiceRequest inValue = new SisComWeb.Services.ServiceFE.SetValueInvoiceRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.SetValueInvoiceRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.CInvoice = CInvoice;
            inValue.Body.DetInvoice = DetInvoice;
            inValue.Body.DocInvoice = DocInvoice;
            inValue.Body.Aditional = Aditional;
            return ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).SetValueInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Services.ServiceFE.SetInvoiceResponse SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.SetInvoice(SisComWeb.Services.ServiceFE.SetInvoiceRequest request) {
            return base.Channel.SetInvoice(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseW SetInvoice(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Services.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Services.ServiceFE.SetInvoiceRequest inValue = new SisComWeb.Services.ServiceFE.SetInvoiceRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.SetInvoiceRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.CInvoice = CInvoice;
            inValue.Body.DetInvoice = DetInvoice;
            inValue.Body.DocInvoice = DocInvoice;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            SisComWeb.Services.ServiceFE.SetInvoiceResponse retVal = ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).SetInvoice(inValue);
            return retVal.Body.SetInvoiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetInvoiceResponse> SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.SetInvoiceAsync(SisComWeb.Services.ServiceFE.SetInvoiceRequest request) {
            return base.Channel.SetInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetInvoiceResponse> SetInvoiceAsync(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Services.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Services.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Services.ServiceFE.SetInvoiceRequest inValue = new SisComWeb.Services.ServiceFE.SetInvoiceRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.SetInvoiceRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.CInvoice = CInvoice;
            inValue.Body.DetInvoice = DetInvoice;
            inValue.Body.DocInvoice = DocInvoice;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            return ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).SetInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Services.ServiceFE.GetValidarDocumentResponse SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.GetValidarDocument(SisComWeb.Services.ServiceFE.GetValidarDocumentRequest request) {
            return base.Channel.GetValidarDocument(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseDocument GetValidarDocument(SisComWeb.Business.ServiceFE.Security Security, string TipoDoc, string Serie, string NroDocument) {
            SisComWeb.Services.ServiceFE.GetValidarDocumentRequest inValue = new SisComWeb.Services.ServiceFE.GetValidarDocumentRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.GetValidarDocumentRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.TipoDoc = TipoDoc;
            inValue.Body.Serie = Serie;
            inValue.Body.NroDocument = NroDocument;
            SisComWeb.Services.ServiceFE.GetValidarDocumentResponse retVal = ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).GetValidarDocument(inValue);
            return retVal.Body.GetValidarDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.GetValidarDocumentResponse> SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.GetValidarDocumentAsync(SisComWeb.Services.ServiceFE.GetValidarDocumentRequest request) {
            return base.Channel.GetValidarDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.GetValidarDocumentResponse> GetValidarDocumentAsync(SisComWeb.Business.ServiceFE.Security Security, string TipoDoc, string Serie, string NroDocument) {
            SisComWeb.Services.ServiceFE.GetValidarDocumentRequest inValue = new SisComWeb.Services.ServiceFE.GetValidarDocumentRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.GetValidarDocumentRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.TipoDoc = TipoDoc;
            inValue.Body.Serie = Serie;
            inValue.Body.NroDocument = NroDocument;
            return ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).GetValidarDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Services.ServiceFE.SetDocumentNoteResponse SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.SetDocumentNote(SisComWeb.Services.ServiceFE.SetDocumentNoteRequest request) {
            return base.Channel.SetDocumentNote(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseW SetDocumentNote(SisComWeb.Business.ServiceFE.Security Security, string Persona, string DocumentNote, SisComWeb.Services.ServiceFE.ArrayOfString DetDocumentNote, SisComWeb.Services.ServiceFE.ArrayOfString DocDocumentNote, SisComWeb.Services.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Services.ServiceFE.SetDocumentNoteRequest inValue = new SisComWeb.Services.ServiceFE.SetDocumentNoteRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.SetDocumentNoteRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.DocumentNote = DocumentNote;
            inValue.Body.DetDocumentNote = DetDocumentNote;
            inValue.Body.DocDocumentNote = DocDocumentNote;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            SisComWeb.Services.ServiceFE.SetDocumentNoteResponse retVal = ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).SetDocumentNote(inValue);
            return retVal.Body.SetDocumentNoteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetDocumentNoteResponse> SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.SetDocumentNoteAsync(SisComWeb.Services.ServiceFE.SetDocumentNoteRequest request) {
            return base.Channel.SetDocumentNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetDocumentNoteResponse> SetDocumentNoteAsync(SisComWeb.Business.ServiceFE.Security Security, string Persona, string DocumentNote, SisComWeb.Services.ServiceFE.ArrayOfString DetDocumentNote, SisComWeb.Services.ServiceFE.ArrayOfString DocDocumentNote, SisComWeb.Services.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Services.ServiceFE.SetDocumentNoteRequest inValue = new SisComWeb.Services.ServiceFE.SetDocumentNoteRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.SetDocumentNoteRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.DocumentNote = DocumentNote;
            inValue.Body.DetDocumentNote = DetDocumentNote;
            inValue.Body.DocDocumentNote = DocDocumentNote;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            return ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).SetDocumentNoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Services.ServiceFE.SetVoidedDocumentResponse SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.SetVoidedDocument(SisComWeb.Services.ServiceFE.SetVoidedDocumentRequest request) {
            return base.Channel.SetVoidedDocument(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseW SetVoidedDocument(SisComWeb.Business.ServiceFE.Security Security, string VoidedDocument) {
            SisComWeb.Services.ServiceFE.SetVoidedDocumentRequest inValue = new SisComWeb.Services.ServiceFE.SetVoidedDocumentRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.SetVoidedDocumentRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.VoidedDocument = VoidedDocument;
            SisComWeb.Services.ServiceFE.SetVoidedDocumentResponse retVal = ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).SetVoidedDocument(inValue);
            return retVal.Body.SetVoidedDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetVoidedDocumentResponse> SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.SetVoidedDocumentAsync(SisComWeb.Services.ServiceFE.SetVoidedDocumentRequest request) {
            return base.Channel.SetVoidedDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetVoidedDocumentResponse> SetVoidedDocumentAsync(SisComWeb.Business.ServiceFE.Security Security, string VoidedDocument) {
            SisComWeb.Services.ServiceFE.SetVoidedDocumentRequest inValue = new SisComWeb.Services.ServiceFE.SetVoidedDocumentRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.SetVoidedDocumentRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.VoidedDocument = VoidedDocument;
            return ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).SetVoidedDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Services.ServiceFE.SetComprobanteRetResponse SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.SetComprobanteRet(SisComWeb.Services.ServiceFE.SetComprobanteRetRequest request) {
            return base.Channel.SetComprobanteRet(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseW SetComprobanteRet(SisComWeb.Business.ServiceFE.Security Security, string Persona, string ComprobanteC, SisComWeb.Services.ServiceFE.ArrayOfString ComprobanteD, SisComWeb.Services.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Services.ServiceFE.SetComprobanteRetRequest inValue = new SisComWeb.Services.ServiceFE.SetComprobanteRetRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.SetComprobanteRetRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.ComprobanteC = ComprobanteC;
            inValue.Body.ComprobanteD = ComprobanteD;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            SisComWeb.Services.ServiceFE.SetComprobanteRetResponse retVal = ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).SetComprobanteRet(inValue);
            return retVal.Body.SetComprobanteRetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetComprobanteRetResponse> SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.SetComprobanteRetAsync(SisComWeb.Services.ServiceFE.SetComprobanteRetRequest request) {
            return base.Channel.SetComprobanteRetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.SetComprobanteRetResponse> SetComprobanteRetAsync(SisComWeb.Business.ServiceFE.Security Security, string Persona, string ComprobanteC, SisComWeb.Services.ServiceFE.ArrayOfString ComprobanteD, SisComWeb.Services.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Services.ServiceFE.SetComprobanteRetRequest inValue = new SisComWeb.Services.ServiceFE.SetComprobanteRetRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.SetComprobanteRetRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.ComprobanteC = ComprobanteC;
            inValue.Body.ComprobanteD = ComprobanteD;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            return ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).SetComprobanteRetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Services.ServiceFE.GetParametroResponse SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.GetParametro(SisComWeb.Services.ServiceFE.GetParametroRequest request) {
            return base.Channel.GetParametro(request);
        }
        
        public SisComWeb.Business.ServiceFE.RParametro GetParametro(SisComWeb.Business.ServiceFE.Security Security) {
            SisComWeb.Services.ServiceFE.GetParametroRequest inValue = new SisComWeb.Services.ServiceFE.GetParametroRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.GetParametroRequestBody();
            inValue.Body.Security = Security;
            SisComWeb.Services.ServiceFE.GetParametroResponse retVal = ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).GetParametro(inValue);
            return retVal.Body.GetParametroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.GetParametroResponse> SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap.GetParametroAsync(SisComWeb.Services.ServiceFE.GetParametroRequest request) {
            return base.Channel.GetParametroAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Services.ServiceFE.GetParametroResponse> GetParametroAsync(SisComWeb.Business.ServiceFE.Security Security) {
            SisComWeb.Services.ServiceFE.GetParametroRequest inValue = new SisComWeb.Services.ServiceFE.GetParametroRequest();
            inValue.Body = new SisComWeb.Services.ServiceFE.GetParametroRequestBody();
            inValue.Body.Security = Security;
            return ((SisComWeb.Services.ServiceFE.Ws_SeeFacteSoap)(this)).GetParametroAsync(inValue);
        }
    }
}
