//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisComWeb.Services.ServicioConsultaDNIRUC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="integradores.jelaf.pe", ConfigurationName="ServicioConsultaDNIRUC.WsConsultaSoap")]
    public interface WsConsultaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RUC del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/CONSULTAR_RUC", ReplyAction="*")]
        SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse CONSULTAR_RUC(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/CONSULTAR_RUC", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse> CONSULTAR_RUCAsync(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DNI del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/CONSULTAR_DNI", ReplyAction="*")]
        SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse CONSULTAR_DNI(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/CONSULTAR_DNI", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse> CONSULTAR_DNIAsync(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CONSULTAR_RUCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CONSULTAR_RUC", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequestBody Body;
        
        public CONSULTAR_RUCRequest() {
        }
        
        public CONSULTAR_RUCRequest(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class CONSULTAR_RUCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RUC;
        
        public CONSULTAR_RUCRequestBody() {
        }
        
        public CONSULTAR_RUCRequestBody(string RUC) {
            this.RUC = RUC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CONSULTAR_RUCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CONSULTAR_RUCResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCResponseBody Body;
        
        public CONSULTAR_RUCResponse() {
        }
        
        public CONSULTAR_RUCResponse(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class CONSULTAR_RUCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServicioConsultaDNIRUC.RUC_Response CONSULTAR_RUCResult;
        
        public CONSULTAR_RUCResponseBody() {
        }
        
        public CONSULTAR_RUCResponseBody(SisComWeb.Business.ServicioConsultaDNIRUC.RUC_Response CONSULTAR_RUCResult) {
            this.CONSULTAR_RUCResult = CONSULTAR_RUCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CONSULTAR_DNIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CONSULTAR_DNI", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequestBody Body;
        
        public CONSULTAR_DNIRequest() {
        }
        
        public CONSULTAR_DNIRequest(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class CONSULTAR_DNIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DNI;
        
        public CONSULTAR_DNIRequestBody() {
        }
        
        public CONSULTAR_DNIRequestBody(string DNI) {
            this.DNI = DNI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CONSULTAR_DNIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CONSULTAR_DNIResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIResponseBody Body;
        
        public CONSULTAR_DNIResponse() {
        }
        
        public CONSULTAR_DNIResponse(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class CONSULTAR_DNIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServicioConsultaDNIRUC.DNI_Response CONSULTAR_DNIResult;
        
        public CONSULTAR_DNIResponseBody() {
        }
        
        public CONSULTAR_DNIResponseBody(SisComWeb.Business.ServicioConsultaDNIRUC.DNI_Response CONSULTAR_DNIResult) {
            this.CONSULTAR_DNIResult = CONSULTAR_DNIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsConsultaSoapChannel : SisComWeb.Services.ServicioConsultaDNIRUC.WsConsultaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsConsultaSoapClient : System.ServiceModel.ClientBase<SisComWeb.Services.ServicioConsultaDNIRUC.WsConsultaSoap>, SisComWeb.Services.ServicioConsultaDNIRUC.WsConsultaSoap {
        
        public WsConsultaSoapClient() {
        }
        
        public WsConsultaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsConsultaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsConsultaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsConsultaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse SisComWeb.Services.ServicioConsultaDNIRUC.WsConsultaSoap.CONSULTAR_RUC(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest request) {
            return base.Channel.CONSULTAR_RUC(request);
        }
        
        public SisComWeb.Business.ServicioConsultaDNIRUC.RUC_Response CONSULTAR_RUC(string RUC) {
            SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest inValue = new SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest();
            inValue.Body = new SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequestBody();
            inValue.Body.RUC = RUC;
            SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse retVal = ((SisComWeb.Services.ServicioConsultaDNIRUC.WsConsultaSoap)(this)).CONSULTAR_RUC(inValue);
            return retVal.Body.CONSULTAR_RUCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse> SisComWeb.Services.ServicioConsultaDNIRUC.WsConsultaSoap.CONSULTAR_RUCAsync(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest request) {
            return base.Channel.CONSULTAR_RUCAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCResponse> CONSULTAR_RUCAsync(string RUC) {
            SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest inValue = new SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequest();
            inValue.Body = new SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_RUCRequestBody();
            inValue.Body.RUC = RUC;
            return ((SisComWeb.Services.ServicioConsultaDNIRUC.WsConsultaSoap)(this)).CONSULTAR_RUCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse SisComWeb.Services.ServicioConsultaDNIRUC.WsConsultaSoap.CONSULTAR_DNI(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest request) {
            return base.Channel.CONSULTAR_DNI(request);
        }
        
        public SisComWeb.Business.ServicioConsultaDNIRUC.DNI_Response CONSULTAR_DNI(string DNI) {
            SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest inValue = new SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest();
            inValue.Body = new SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequestBody();
            inValue.Body.DNI = DNI;
            SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse retVal = ((SisComWeb.Services.ServicioConsultaDNIRUC.WsConsultaSoap)(this)).CONSULTAR_DNI(inValue);
            return retVal.Body.CONSULTAR_DNIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse> SisComWeb.Services.ServicioConsultaDNIRUC.WsConsultaSoap.CONSULTAR_DNIAsync(SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest request) {
            return base.Channel.CONSULTAR_DNIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIResponse> CONSULTAR_DNIAsync(string DNI) {
            SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest inValue = new SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequest();
            inValue.Body = new SisComWeb.Services.ServicioConsultaDNIRUC.CONSULTAR_DNIRequestBody();
            inValue.Body.DNI = DNI;
            return ((SisComWeb.Services.ServicioConsultaDNIRUC.WsConsultaSoap)(this)).CONSULTAR_DNIAsync(inValue);
        }
    }
}
