//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisComWeb.Business.ServiceFE {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Security", Namespace="integradores.jelaf.pe")]
    [System.SerializableAttribute()]
    public partial class Security : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="integradores.jelaf.pe", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseW", Namespace="integradores.jelaf.pe")]
    [System.SerializableAttribute()]
    public partial class ResponseW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoSunatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeSunatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlCertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlSUNATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PdfValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodError {
            get {
                return this.CodErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodErrorField, value) != true)) {
                    this.CodErrorField = value;
                    this.RaisePropertyChanged("CodError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EstadoSunat {
            get {
                return this.EstadoSunatField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoSunatField, value) != true)) {
                    this.EstadoSunatField = value;
                    this.RaisePropertyChanged("EstadoSunat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MensajeSunat {
            get {
                return this.MensajeSunatField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeSunatField, value) != true)) {
                    this.MensajeSunatField = value;
                    this.RaisePropertyChanged("MensajeSunat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string XmlCert {
            get {
                return this.XmlCertField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlCertField, value) != true)) {
                    this.XmlCertField = value;
                    this.RaisePropertyChanged("XmlCert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string XmlSUNAT {
            get {
                return this.XmlSUNATField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlSUNATField, value) != true)) {
                    this.XmlSUNATField = value;
                    this.RaisePropertyChanged("XmlSUNAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NombreArchivo {
            get {
                return this.NombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArchivoField, value) != true)) {
                    this.NombreArchivoField = value;
                    this.RaisePropertyChanged("NombreArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SignatureValue {
            get {
                return this.SignatureValueField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureValueField, value) != true)) {
                    this.SignatureValueField = value;
                    this.RaisePropertyChanged("SignatureValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string PdfValue {
            get {
                return this.PdfValueField;
            }
            set {
                if ((object.ReferenceEquals(this.PdfValueField, value) != true)) {
                    this.PdfValueField = value;
                    this.RaisePropertyChanged("PdfValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDocument", Namespace="integradores.jelaf.pe")]
    [System.SerializableAttribute()]
    public partial class ResponseDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        private bool ExisteDocumentField;
        
        private short EstadoDocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoRespuestaSunatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool ExisteDocument {
            get {
                return this.ExisteDocumentField;
            }
            set {
                if ((this.ExisteDocumentField.Equals(value) != true)) {
                    this.ExisteDocumentField = value;
                    this.RaisePropertyChanged("ExisteDocument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public short EstadoDocument {
            get {
                return this.EstadoDocumentField;
            }
            set {
                if ((this.EstadoDocumentField.Equals(value) != true)) {
                    this.EstadoDocumentField = value;
                    this.RaisePropertyChanged("EstadoDocument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EstadoRespuestaSunat {
            get {
                return this.EstadoRespuestaSunatField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoRespuestaSunatField, value) != true)) {
                    this.EstadoRespuestaSunatField = value;
                    this.RaisePropertyChanged("EstadoRespuestaSunat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SignatureValue {
            get {
                return this.SignatureValueField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureValueField, value) != true)) {
                    this.SignatureValueField = value;
                    this.RaisePropertyChanged("SignatureValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RParametro", Namespace="integradores.jelaf.pe")]
    [System.SerializableAttribute()]
    public partial class RParametro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SisComWeb.Business.ServiceFE.Rempresa RempresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SisComWeb.Business.ServiceFE.FE_TipoDocumentNote> RDocumentNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SisComWeb.Business.ServiceFE.FE_UnidadMedidaSUNAT> RUnidadMedidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SisComWeb.Business.ServiceFE.Rempresa Rempresa {
            get {
                return this.RempresaField;
            }
            set {
                if ((object.ReferenceEquals(this.RempresaField, value) != true)) {
                    this.RempresaField = value;
                    this.RaisePropertyChanged("Rempresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<SisComWeb.Business.ServiceFE.FE_TipoDocumentNote> RDocumentNote {
            get {
                return this.RDocumentNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.RDocumentNoteField, value) != true)) {
                    this.RDocumentNoteField = value;
                    this.RaisePropertyChanged("RDocumentNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.Generic.List<SisComWeb.Business.ServiceFE.FE_UnidadMedidaSUNAT> RUnidadMedida {
            get {
                return this.RUnidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.RUnidadMedidaField, value) != true)) {
                    this.RUnidadMedidaField = value;
                    this.RaisePropertyChanged("RUnidadMedida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rempresa", Namespace="integradores.jelaf.pe")]
    [System.SerializableAttribute()]
    public partial class Rempresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbigeoSunatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResolucionAutorizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaginaWebEmisorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RucEmpresa {
            get {
                return this.RucEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.RucEmpresaField, value) != true)) {
                    this.RucEmpresaField = value;
                    this.RaisePropertyChanged("RucEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DirFiscal {
            get {
                return this.DirFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.DirFiscalField, value) != true)) {
                    this.DirFiscalField = value;
                    this.RaisePropertyChanged("DirFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UbigeoSunat {
            get {
                return this.UbigeoSunatField;
            }
            set {
                if ((object.ReferenceEquals(this.UbigeoSunatField, value) != true)) {
                    this.UbigeoSunatField = value;
                    this.RaisePropertyChanged("UbigeoSunat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ResolucionAutorizado {
            get {
                return this.ResolucionAutorizadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResolucionAutorizadoField, value) != true)) {
                    this.ResolucionAutorizadoField = value;
                    this.RaisePropertyChanged("ResolucionAutorizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PaginaWebEmisor {
            get {
                return this.PaginaWebEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.PaginaWebEmisorField, value) != true)) {
                    this.PaginaWebEmisorField = value;
                    this.RaisePropertyChanged("PaginaWebEmisor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FE_TipoDocumentNote", Namespace="integradores.jelaf.pe")]
    [System.SerializableAttribute()]
    public partial class FE_TipoDocumentNote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodMotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodDocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodMotivo {
            get {
                return this.CodMotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodMotivoField, value) != true)) {
                    this.CodMotivoField = value;
                    this.RaisePropertyChanged("CodMotivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodDoc {
            get {
                return this.CodDocField;
            }
            set {
                if ((object.ReferenceEquals(this.CodDocField, value) != true)) {
                    this.CodDocField = value;
                    this.RaisePropertyChanged("CodDoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FE_UnidadMedidaSUNAT", Namespace="integradores.jelaf.pe")]
    [System.SerializableAttribute()]
    public partial class FE_UnidadMedidaSUNAT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodUnivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbrevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodUniv {
            get {
                return this.CodUnivField;
            }
            set {
                if ((object.ReferenceEquals(this.CodUnivField, value) != true)) {
                    this.CodUnivField = value;
                    this.RaisePropertyChanged("CodUniv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Abrev {
            get {
                return this.AbrevField;
            }
            set {
                if ((object.ReferenceEquals(this.AbrevField, value) != true)) {
                    this.AbrevField = value;
                    this.RaisePropertyChanged("Abrev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="integradores.jelaf.pe", ConfigurationName="ServiceFE.Ws_SeeFacteSoap")]
    public interface Ws_SeeFacteSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetValueInvoice", ReplyAction="*")]
        SisComWeb.Business.ServiceFE.SetValueInvoiceResponse SetValueInvoice(SisComWeb.Business.ServiceFE.SetValueInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetValueInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetValueInvoiceResponse> SetValueInvoiceAsync(SisComWeb.Business.ServiceFE.SetValueInvoiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetInvoice", ReplyAction="*")]
        SisComWeb.Business.ServiceFE.SetInvoiceResponse SetInvoice(SisComWeb.Business.ServiceFE.SetInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetInvoiceResponse> SetInvoiceAsync(SisComWeb.Business.ServiceFE.SetInvoiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/GetValidarDocument", ReplyAction="*")]
        SisComWeb.Business.ServiceFE.GetValidarDocumentResponse GetValidarDocument(SisComWeb.Business.ServiceFE.GetValidarDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/GetValidarDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.GetValidarDocumentResponse> GetValidarDocumentAsync(SisComWeb.Business.ServiceFE.GetValidarDocumentRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetDocumentNote", ReplyAction="*")]
        SisComWeb.Business.ServiceFE.SetDocumentNoteResponse SetDocumentNote(SisComWeb.Business.ServiceFE.SetDocumentNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetDocumentNote", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetDocumentNoteResponse> SetDocumentNoteAsync(SisComWeb.Business.ServiceFE.SetDocumentNoteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetVoidedDocument", ReplyAction="*")]
        SisComWeb.Business.ServiceFE.SetVoidedDocumentResponse SetVoidedDocument(SisComWeb.Business.ServiceFE.SetVoidedDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetVoidedDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetVoidedDocumentResponse> SetVoidedDocumentAsync(SisComWeb.Business.ServiceFE.SetVoidedDocumentRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetComprobanteRet", ReplyAction="*")]
        SisComWeb.Business.ServiceFE.SetComprobanteRetResponse SetComprobanteRet(SisComWeb.Business.ServiceFE.SetComprobanteRetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/SetComprobanteRet", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetComprobanteRetResponse> SetComprobanteRetAsync(SisComWeb.Business.ServiceFE.SetComprobanteRetRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Security del espacio de nombres integradores.jelaf.pe no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/GetParametro", ReplyAction="*")]
        SisComWeb.Business.ServiceFE.GetParametroResponse GetParametro(SisComWeb.Business.ServiceFE.GetParametroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="integradores.jelaf.pe/GetParametro", ReplyAction="*")]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.GetParametroResponse> GetParametroAsync(SisComWeb.Business.ServiceFE.GetParametroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetValueInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetValueInvoice", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.SetValueInvoiceRequestBody Body;
        
        public SetValueInvoiceRequest() {
        }
        
        public SetValueInvoiceRequest(SisComWeb.Business.ServiceFE.SetValueInvoiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetValueInvoiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Persona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SisComWeb.Business.ServiceFE.ArrayOfString DetInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SisComWeb.Business.ServiceFE.ArrayOfString DocInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SisComWeb.Business.ServiceFE.ArrayOfString Aditional;
        
        public SetValueInvoiceRequestBody() {
        }
        
        public SetValueInvoiceRequestBody(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Business.ServiceFE.ArrayOfString Aditional) {
            this.Security = Security;
            this.Persona = Persona;
            this.CInvoice = CInvoice;
            this.DetInvoice = DetInvoice;
            this.DocInvoice = DocInvoice;
            this.Aditional = Aditional;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetValueInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetValueInvoiceResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.SetValueInvoiceResponseBody Body;
        
        public SetValueInvoiceResponse() {
        }
        
        public SetValueInvoiceResponse(SisComWeb.Business.ServiceFE.SetValueInvoiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetValueInvoiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseW SetValueInvoiceResult;
        
        public SetValueInvoiceResponseBody() {
        }
        
        public SetValueInvoiceResponseBody(SisComWeb.Business.ServiceFE.ResponseW SetValueInvoiceResult) {
            this.SetValueInvoiceResult = SetValueInvoiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetInvoice", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.SetInvoiceRequestBody Body;
        
        public SetInvoiceRequest() {
        }
        
        public SetInvoiceRequest(SisComWeb.Business.ServiceFE.SetInvoiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetInvoiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Persona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SisComWeb.Business.ServiceFE.ArrayOfString DetInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SisComWeb.Business.ServiceFE.ArrayOfString DocInvoice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SisComWeb.Business.ServiceFE.ArrayOfString Aditional;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool EnvioAsync;
        
        public SetInvoiceRequestBody() {
        }
        
        public SetInvoiceRequestBody(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Business.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            this.Security = Security;
            this.Persona = Persona;
            this.CInvoice = CInvoice;
            this.DetInvoice = DetInvoice;
            this.DocInvoice = DocInvoice;
            this.Aditional = Aditional;
            this.EnvioAsync = EnvioAsync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetInvoiceResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.SetInvoiceResponseBody Body;
        
        public SetInvoiceResponse() {
        }
        
        public SetInvoiceResponse(SisComWeb.Business.ServiceFE.SetInvoiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetInvoiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseW SetInvoiceResult;
        
        public SetInvoiceResponseBody() {
        }
        
        public SetInvoiceResponseBody(SisComWeb.Business.ServiceFE.ResponseW SetInvoiceResult) {
            this.SetInvoiceResult = SetInvoiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValidarDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValidarDocument", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.GetValidarDocumentRequestBody Body;
        
        public GetValidarDocumentRequest() {
        }
        
        public GetValidarDocumentRequest(SisComWeb.Business.ServiceFE.GetValidarDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class GetValidarDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TipoDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Serie;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NroDocument;
        
        public GetValidarDocumentRequestBody() {
        }
        
        public GetValidarDocumentRequestBody(SisComWeb.Business.ServiceFE.Security Security, string TipoDoc, string Serie, string NroDocument) {
            this.Security = Security;
            this.TipoDoc = TipoDoc;
            this.Serie = Serie;
            this.NroDocument = NroDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValidarDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValidarDocumentResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.GetValidarDocumentResponseBody Body;
        
        public GetValidarDocumentResponse() {
        }
        
        public GetValidarDocumentResponse(SisComWeb.Business.ServiceFE.GetValidarDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class GetValidarDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseDocument GetValidarDocumentResult;
        
        public GetValidarDocumentResponseBody() {
        }
        
        public GetValidarDocumentResponseBody(SisComWeb.Business.ServiceFE.ResponseDocument GetValidarDocumentResult) {
            this.GetValidarDocumentResult = GetValidarDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDocumentNoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDocumentNote", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.SetDocumentNoteRequestBody Body;
        
        public SetDocumentNoteRequest() {
        }
        
        public SetDocumentNoteRequest(SisComWeb.Business.ServiceFE.SetDocumentNoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetDocumentNoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Persona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DocumentNote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SisComWeb.Business.ServiceFE.ArrayOfString DetDocumentNote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SisComWeb.Business.ServiceFE.ArrayOfString DocDocumentNote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SisComWeb.Business.ServiceFE.ArrayOfString Aditional;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool EnvioAsync;
        
        public SetDocumentNoteRequestBody() {
        }
        
        public SetDocumentNoteRequestBody(SisComWeb.Business.ServiceFE.Security Security, string Persona, string DocumentNote, SisComWeb.Business.ServiceFE.ArrayOfString DetDocumentNote, SisComWeb.Business.ServiceFE.ArrayOfString DocDocumentNote, SisComWeb.Business.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            this.Security = Security;
            this.Persona = Persona;
            this.DocumentNote = DocumentNote;
            this.DetDocumentNote = DetDocumentNote;
            this.DocDocumentNote = DocDocumentNote;
            this.Aditional = Aditional;
            this.EnvioAsync = EnvioAsync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDocumentNoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDocumentNoteResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.SetDocumentNoteResponseBody Body;
        
        public SetDocumentNoteResponse() {
        }
        
        public SetDocumentNoteResponse(SisComWeb.Business.ServiceFE.SetDocumentNoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetDocumentNoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseW SetDocumentNoteResult;
        
        public SetDocumentNoteResponseBody() {
        }
        
        public SetDocumentNoteResponseBody(SisComWeb.Business.ServiceFE.ResponseW SetDocumentNoteResult) {
            this.SetDocumentNoteResult = SetDocumentNoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetVoidedDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetVoidedDocument", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.SetVoidedDocumentRequestBody Body;
        
        public SetVoidedDocumentRequest() {
        }
        
        public SetVoidedDocumentRequest(SisComWeb.Business.ServiceFE.SetVoidedDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetVoidedDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string VoidedDocument;
        
        public SetVoidedDocumentRequestBody() {
        }
        
        public SetVoidedDocumentRequestBody(SisComWeb.Business.ServiceFE.Security Security, string VoidedDocument) {
            this.Security = Security;
            this.VoidedDocument = VoidedDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetVoidedDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetVoidedDocumentResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.SetVoidedDocumentResponseBody Body;
        
        public SetVoidedDocumentResponse() {
        }
        
        public SetVoidedDocumentResponse(SisComWeb.Business.ServiceFE.SetVoidedDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetVoidedDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseW SetVoidedDocumentResult;
        
        public SetVoidedDocumentResponseBody() {
        }
        
        public SetVoidedDocumentResponseBody(SisComWeb.Business.ServiceFE.ResponseW SetVoidedDocumentResult) {
            this.SetVoidedDocumentResult = SetVoidedDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetComprobanteRetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetComprobanteRet", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.SetComprobanteRetRequestBody Body;
        
        public SetComprobanteRetRequest() {
        }
        
        public SetComprobanteRetRequest(SisComWeb.Business.ServiceFE.SetComprobanteRetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetComprobanteRetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Persona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ComprobanteC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SisComWeb.Business.ServiceFE.ArrayOfString ComprobanteD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SisComWeb.Business.ServiceFE.ArrayOfString Aditional;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool EnvioAsync;
        
        public SetComprobanteRetRequestBody() {
        }
        
        public SetComprobanteRetRequestBody(SisComWeb.Business.ServiceFE.Security Security, string Persona, string ComprobanteC, SisComWeb.Business.ServiceFE.ArrayOfString ComprobanteD, SisComWeb.Business.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            this.Security = Security;
            this.Persona = Persona;
            this.ComprobanteC = ComprobanteC;
            this.ComprobanteD = ComprobanteD;
            this.Aditional = Aditional;
            this.EnvioAsync = EnvioAsync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetComprobanteRetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetComprobanteRetResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.SetComprobanteRetResponseBody Body;
        
        public SetComprobanteRetResponse() {
        }
        
        public SetComprobanteRetResponse(SisComWeb.Business.ServiceFE.SetComprobanteRetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class SetComprobanteRetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.ResponseW SetComprobanteRetResult;
        
        public SetComprobanteRetResponseBody() {
        }
        
        public SetComprobanteRetResponseBody(SisComWeb.Business.ServiceFE.ResponseW SetComprobanteRetResult) {
            this.SetComprobanteRetResult = SetComprobanteRetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParametroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParametro", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.GetParametroRequestBody Body;
        
        public GetParametroRequest() {
        }
        
        public GetParametroRequest(SisComWeb.Business.ServiceFE.GetParametroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class GetParametroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.Security Security;
        
        public GetParametroRequestBody() {
        }
        
        public GetParametroRequestBody(SisComWeb.Business.ServiceFE.Security Security) {
            this.Security = Security;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParametroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParametroResponse", Namespace="integradores.jelaf.pe", Order=0)]
        public SisComWeb.Business.ServiceFE.GetParametroResponseBody Body;
        
        public GetParametroResponse() {
        }
        
        public GetParametroResponse(SisComWeb.Business.ServiceFE.GetParametroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="integradores.jelaf.pe")]
    public partial class GetParametroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SisComWeb.Business.ServiceFE.RParametro GetParametroResult;
        
        public GetParametroResponseBody() {
        }
        
        public GetParametroResponseBody(SisComWeb.Business.ServiceFE.RParametro GetParametroResult) {
            this.GetParametroResult = GetParametroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Ws_SeeFacteSoapChannel : SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ws_SeeFacteSoapClient : System.ServiceModel.ClientBase<SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap>, SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap {
        
        public Ws_SeeFacteSoapClient() {
        }
        
        public Ws_SeeFacteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ws_SeeFacteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_SeeFacteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_SeeFacteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Business.ServiceFE.SetValueInvoiceResponse SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.SetValueInvoice(SisComWeb.Business.ServiceFE.SetValueInvoiceRequest request) {
            return base.Channel.SetValueInvoice(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseW SetValueInvoice(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Business.ServiceFE.ArrayOfString Aditional) {
            SisComWeb.Business.ServiceFE.SetValueInvoiceRequest inValue = new SisComWeb.Business.ServiceFE.SetValueInvoiceRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.SetValueInvoiceRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.CInvoice = CInvoice;
            inValue.Body.DetInvoice = DetInvoice;
            inValue.Body.DocInvoice = DocInvoice;
            inValue.Body.Aditional = Aditional;
            SisComWeb.Business.ServiceFE.SetValueInvoiceResponse retVal = ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).SetValueInvoice(inValue);
            return retVal.Body.SetValueInvoiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetValueInvoiceResponse> SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.SetValueInvoiceAsync(SisComWeb.Business.ServiceFE.SetValueInvoiceRequest request) {
            return base.Channel.SetValueInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetValueInvoiceResponse> SetValueInvoiceAsync(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Business.ServiceFE.ArrayOfString Aditional) {
            SisComWeb.Business.ServiceFE.SetValueInvoiceRequest inValue = new SisComWeb.Business.ServiceFE.SetValueInvoiceRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.SetValueInvoiceRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.CInvoice = CInvoice;
            inValue.Body.DetInvoice = DetInvoice;
            inValue.Body.DocInvoice = DocInvoice;
            inValue.Body.Aditional = Aditional;
            return ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).SetValueInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Business.ServiceFE.SetInvoiceResponse SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.SetInvoice(SisComWeb.Business.ServiceFE.SetInvoiceRequest request) {
            return base.Channel.SetInvoice(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseW SetInvoice(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Business.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Business.ServiceFE.SetInvoiceRequest inValue = new SisComWeb.Business.ServiceFE.SetInvoiceRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.SetInvoiceRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.CInvoice = CInvoice;
            inValue.Body.DetInvoice = DetInvoice;
            inValue.Body.DocInvoice = DocInvoice;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            SisComWeb.Business.ServiceFE.SetInvoiceResponse retVal = ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).SetInvoice(inValue);
            return retVal.Body.SetInvoiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetInvoiceResponse> SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.SetInvoiceAsync(SisComWeb.Business.ServiceFE.SetInvoiceRequest request) {
            return base.Channel.SetInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetInvoiceResponse> SetInvoiceAsync(SisComWeb.Business.ServiceFE.Security Security, string Persona, string CInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DetInvoice, SisComWeb.Business.ServiceFE.ArrayOfString DocInvoice, SisComWeb.Business.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Business.ServiceFE.SetInvoiceRequest inValue = new SisComWeb.Business.ServiceFE.SetInvoiceRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.SetInvoiceRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.CInvoice = CInvoice;
            inValue.Body.DetInvoice = DetInvoice;
            inValue.Body.DocInvoice = DocInvoice;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            return ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).SetInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Business.ServiceFE.GetValidarDocumentResponse SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.GetValidarDocument(SisComWeb.Business.ServiceFE.GetValidarDocumentRequest request) {
            return base.Channel.GetValidarDocument(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseDocument GetValidarDocument(SisComWeb.Business.ServiceFE.Security Security, string TipoDoc, string Serie, string NroDocument) {
            SisComWeb.Business.ServiceFE.GetValidarDocumentRequest inValue = new SisComWeb.Business.ServiceFE.GetValidarDocumentRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.GetValidarDocumentRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.TipoDoc = TipoDoc;
            inValue.Body.Serie = Serie;
            inValue.Body.NroDocument = NroDocument;
            SisComWeb.Business.ServiceFE.GetValidarDocumentResponse retVal = ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).GetValidarDocument(inValue);
            return retVal.Body.GetValidarDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.GetValidarDocumentResponse> SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.GetValidarDocumentAsync(SisComWeb.Business.ServiceFE.GetValidarDocumentRequest request) {
            return base.Channel.GetValidarDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.GetValidarDocumentResponse> GetValidarDocumentAsync(SisComWeb.Business.ServiceFE.Security Security, string TipoDoc, string Serie, string NroDocument) {
            SisComWeb.Business.ServiceFE.GetValidarDocumentRequest inValue = new SisComWeb.Business.ServiceFE.GetValidarDocumentRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.GetValidarDocumentRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.TipoDoc = TipoDoc;
            inValue.Body.Serie = Serie;
            inValue.Body.NroDocument = NroDocument;
            return ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).GetValidarDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Business.ServiceFE.SetDocumentNoteResponse SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.SetDocumentNote(SisComWeb.Business.ServiceFE.SetDocumentNoteRequest request) {
            return base.Channel.SetDocumentNote(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseW SetDocumentNote(SisComWeb.Business.ServiceFE.Security Security, string Persona, string DocumentNote, SisComWeb.Business.ServiceFE.ArrayOfString DetDocumentNote, SisComWeb.Business.ServiceFE.ArrayOfString DocDocumentNote, SisComWeb.Business.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Business.ServiceFE.SetDocumentNoteRequest inValue = new SisComWeb.Business.ServiceFE.SetDocumentNoteRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.SetDocumentNoteRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.DocumentNote = DocumentNote;
            inValue.Body.DetDocumentNote = DetDocumentNote;
            inValue.Body.DocDocumentNote = DocDocumentNote;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            SisComWeb.Business.ServiceFE.SetDocumentNoteResponse retVal = ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).SetDocumentNote(inValue);
            return retVal.Body.SetDocumentNoteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetDocumentNoteResponse> SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.SetDocumentNoteAsync(SisComWeb.Business.ServiceFE.SetDocumentNoteRequest request) {
            return base.Channel.SetDocumentNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetDocumentNoteResponse> SetDocumentNoteAsync(SisComWeb.Business.ServiceFE.Security Security, string Persona, string DocumentNote, SisComWeb.Business.ServiceFE.ArrayOfString DetDocumentNote, SisComWeb.Business.ServiceFE.ArrayOfString DocDocumentNote, SisComWeb.Business.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Business.ServiceFE.SetDocumentNoteRequest inValue = new SisComWeb.Business.ServiceFE.SetDocumentNoteRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.SetDocumentNoteRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.DocumentNote = DocumentNote;
            inValue.Body.DetDocumentNote = DetDocumentNote;
            inValue.Body.DocDocumentNote = DocDocumentNote;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            return ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).SetDocumentNoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Business.ServiceFE.SetVoidedDocumentResponse SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.SetVoidedDocument(SisComWeb.Business.ServiceFE.SetVoidedDocumentRequest request) {
            return base.Channel.SetVoidedDocument(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseW SetVoidedDocument(SisComWeb.Business.ServiceFE.Security Security, string VoidedDocument) {
            SisComWeb.Business.ServiceFE.SetVoidedDocumentRequest inValue = new SisComWeb.Business.ServiceFE.SetVoidedDocumentRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.SetVoidedDocumentRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.VoidedDocument = VoidedDocument;
            SisComWeb.Business.ServiceFE.SetVoidedDocumentResponse retVal = ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).SetVoidedDocument(inValue);
            return retVal.Body.SetVoidedDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetVoidedDocumentResponse> SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.SetVoidedDocumentAsync(SisComWeb.Business.ServiceFE.SetVoidedDocumentRequest request) {
            return base.Channel.SetVoidedDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetVoidedDocumentResponse> SetVoidedDocumentAsync(SisComWeb.Business.ServiceFE.Security Security, string VoidedDocument) {
            SisComWeb.Business.ServiceFE.SetVoidedDocumentRequest inValue = new SisComWeb.Business.ServiceFE.SetVoidedDocumentRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.SetVoidedDocumentRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.VoidedDocument = VoidedDocument;
            return ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).SetVoidedDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Business.ServiceFE.SetComprobanteRetResponse SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.SetComprobanteRet(SisComWeb.Business.ServiceFE.SetComprobanteRetRequest request) {
            return base.Channel.SetComprobanteRet(request);
        }
        
        public SisComWeb.Business.ServiceFE.ResponseW SetComprobanteRet(SisComWeb.Business.ServiceFE.Security Security, string Persona, string ComprobanteC, SisComWeb.Business.ServiceFE.ArrayOfString ComprobanteD, SisComWeb.Business.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Business.ServiceFE.SetComprobanteRetRequest inValue = new SisComWeb.Business.ServiceFE.SetComprobanteRetRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.SetComprobanteRetRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.ComprobanteC = ComprobanteC;
            inValue.Body.ComprobanteD = ComprobanteD;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            SisComWeb.Business.ServiceFE.SetComprobanteRetResponse retVal = ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).SetComprobanteRet(inValue);
            return retVal.Body.SetComprobanteRetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetComprobanteRetResponse> SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.SetComprobanteRetAsync(SisComWeb.Business.ServiceFE.SetComprobanteRetRequest request) {
            return base.Channel.SetComprobanteRetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.SetComprobanteRetResponse> SetComprobanteRetAsync(SisComWeb.Business.ServiceFE.Security Security, string Persona, string ComprobanteC, SisComWeb.Business.ServiceFE.ArrayOfString ComprobanteD, SisComWeb.Business.ServiceFE.ArrayOfString Aditional, bool EnvioAsync) {
            SisComWeb.Business.ServiceFE.SetComprobanteRetRequest inValue = new SisComWeb.Business.ServiceFE.SetComprobanteRetRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.SetComprobanteRetRequestBody();
            inValue.Body.Security = Security;
            inValue.Body.Persona = Persona;
            inValue.Body.ComprobanteC = ComprobanteC;
            inValue.Body.ComprobanteD = ComprobanteD;
            inValue.Body.Aditional = Aditional;
            inValue.Body.EnvioAsync = EnvioAsync;
            return ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).SetComprobanteRetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisComWeb.Business.ServiceFE.GetParametroResponse SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.GetParametro(SisComWeb.Business.ServiceFE.GetParametroRequest request) {
            return base.Channel.GetParametro(request);
        }
        
        public SisComWeb.Business.ServiceFE.RParametro GetParametro(SisComWeb.Business.ServiceFE.Security Security) {
            SisComWeb.Business.ServiceFE.GetParametroRequest inValue = new SisComWeb.Business.ServiceFE.GetParametroRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.GetParametroRequestBody();
            inValue.Body.Security = Security;
            SisComWeb.Business.ServiceFE.GetParametroResponse retVal = ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).GetParametro(inValue);
            return retVal.Body.GetParametroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.GetParametroResponse> SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap.GetParametroAsync(SisComWeb.Business.ServiceFE.GetParametroRequest request) {
            return base.Channel.GetParametroAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisComWeb.Business.ServiceFE.GetParametroResponse> GetParametroAsync(SisComWeb.Business.ServiceFE.Security Security) {
            SisComWeb.Business.ServiceFE.GetParametroRequest inValue = new SisComWeb.Business.ServiceFE.GetParametroRequest();
            inValue.Body = new SisComWeb.Business.ServiceFE.GetParametroRequestBody();
            inValue.Body.Security = Security;
            return ((SisComWeb.Business.ServiceFE.Ws_SeeFacteSoap)(this)).GetParametroAsync(inValue);
        }
    }
}
